services:
  eshopdb:
    image: postgres

  seq:
    image: datalust/seq:latest

  distributedcache:
      image: redis:latest

  messagebus:
    image: rabbitmq:management
    
volumes:
  postgres_eshopdb:

networks:
  eshop_network:

