services:
    eshopdb:
        container_name: eshopdb
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=EShopDb
        ports:
          - "5432:5432"
        volumes:
          - postgres_eshopdb:/var/lib/postgresql/data
        networks:
            - eshop_network

    pgadmin:
        image: dpage/pgadmin4 
        container_name: pgadmin
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        depends_on:
            - eshopdb
        networks:
          - eshop_network