services:
    eshopdb:
        container_name: eshopdb
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=EShopDb
        ports:
          - "5432:5432"
        volumes:
          - postgres_eshopdb:/var/lib/postgresql/data
        networks:
            - eshop_network

    seq:
        container_name: seq
        environment:
            - ACCEPT_EULA=Y
        restart: always
        ports:
            - "5341:5341"
            - "9091:80"  
    
    distributedcache:
        container_name: distributedcache
        restart: always
        ports:
            - "6379:6379"
        networks:
            - eshop_network
    
    messagebus:
        container_name: messagebus
        hostname: ecommerce-mq
        environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
        restart: always
        ports:
          - "5672:5672"
          - "15672:15672"

    pgadmin:
        image: dpage/pgadmin4 
        container_name: pgadmin
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        depends_on:
            - eshopdb
        networks:
          - eshop_network

    identity:
        container_name: identity
        environment:
          - KEYCLOAK_ADMIN=admin
          - KEYCLOAK_ADMIN_PASSWORD=admin
          - KC_DB=postgres
          - KC_DB_URL=jdbc:postgresql://eshopdb/EShopDb?currentSchema=identity
          - KC_DB_USERNAME=postgres
          - KC_DB_PASSWORD=postgres
          # - KC_HOSTNAME=http://identity:9090/
          # - KC_HTTP_PORT=9090
        restart: always
        ports:
          # - "9090:9090"
            - "9090:8080"   
        command:
          - start-dev
        networks:
            - eshop_network